"""
Local Indian food database. Nutritional values per 100g (cooked/ready-to-eat unless noted).
Source: ICMR/NIN Indian Food Composition Tables + standard published values.
"""

INDIAN_FOODS: list[dict] = [
    # ─── RICE & RICE DISHES ──────────────────────────────────────────────────
    {
        "food_name": "White Rice (Cooked)",
        "tags": ["white rice", "rice", "chawal", "plain rice", "steamed rice", "cooked rice"],
        "calories_per_100g": 130, "protein_per_100g": 2.7, "carbs_per_100g": 28.0, "fat_per_100g": 0.3,
        "serving_description": "1 cup (200g)", "serving_weight_g": 200,
    },
    {
        "food_name": "Brown Rice (Cooked)",
        "tags": ["brown rice", "whole grain rice"],
        "calories_per_100g": 112, "protein_per_100g": 2.6, "carbs_per_100g": 23.0, "fat_per_100g": 0.9,
        "serving_description": "1 cup (195g)", "serving_weight_g": 195,
    },
    {
        "food_name": "Basmati Rice (Cooked)",
        "tags": ["basmati", "basmati rice", "long grain rice"],
        "calories_per_100g": 121, "protein_per_100g": 3.5, "carbs_per_100g": 25.2, "fat_per_100g": 0.4,
        "serving_description": "1 cup (195g)", "serving_weight_g": 195,
    },
    {
        "food_name": "Curd Rice",
        "tags": ["curd rice", "thayir sadam", "dahi chawal", "yogurt rice"],
        "calories_per_100g": 97, "protein_per_100g": 3.5, "carbs_per_100g": 17.0, "fat_per_100g": 1.8,
        "serving_description": "1 bowl (200g)", "serving_weight_g": 200,
    },
    {
        "food_name": "Chicken Biryani",
        "tags": ["chicken biryani", "biryani", "dum biryani", "hyderabadi biryani"],
        "calories_per_100g": 185, "protein_per_100g": 11.0, "carbs_per_100g": 25.0, "fat_per_100g": 5.0,
        "serving_description": "1 plate (300g)", "serving_weight_g": 300,
    },
    {
        "food_name": "Mutton Biryani",
        "tags": ["mutton biryani", "lamb biryani", "gosht biryani"],
        "calories_per_100g": 200, "protein_per_100g": 12.0, "carbs_per_100g": 25.0, "fat_per_100g": 6.0,
        "serving_description": "1 plate (300g)", "serving_weight_g": 300,
    },
    {
        "food_name": "Vegetable Biryani",
        "tags": ["veg biryani", "vegetable biryani"],
        "calories_per_100g": 130, "protein_per_100g": 4.0, "carbs_per_100g": 24.0, "fat_per_100g": 3.0,
        "serving_description": "1 plate (300g)", "serving_weight_g": 300,
    },
    {
        "food_name": "Pulao",
        "tags": ["pulao", "pilaf", "veg pulao", "vegetable pulao", "peas pulao", "matar pulao"],
        "calories_per_100g": 140, "protein_per_100g": 3.5, "carbs_per_100g": 25.0, "fat_per_100g": 3.5,
        "serving_description": "1 bowl (200g)", "serving_weight_g": 200,
    },
    {
        "food_name": "Khichdi",
        "tags": ["khichdi", "khichri", "dal khichdi", "moong khichdi"],
        "calories_per_100g": 110, "protein_per_100g": 5.0, "carbs_per_100g": 20.0, "fat_per_100g": 2.0,
        "serving_description": "1 bowl (200g)", "serving_weight_g": 200,
    },
    {
        "food_name": "Sabudana Khichdi",
        "tags": ["sabudana khichdi", "sago khichdi", "tapioca khichdi"],
        "calories_per_100g": 185, "protein_per_100g": 2.0, "carbs_per_100g": 35.0, "fat_per_100g": 4.0,
        "serving_description": "1 bowl (200g)", "serving_weight_g": 200,
    },
    # ─── FLATBREADS ──────────────────────────────────────────────────────────
    {
        "food_name": "Chapati / Roti",
        "tags": ["chapati", "roti", "phulka", "wheat roti", "whole wheat roti"],
        "calories_per_100g": 265, "protein_per_100g": 8.5, "carbs_per_100g": 50.0, "fat_per_100g": 4.5,
        "serving_description": "1 roti (35g)", "serving_weight_g": 35,
    },
    {
        "food_name": "Paratha",
        "tags": ["paratha", "aloo paratha", "stuffed paratha", "plain paratha"],
        "calories_per_100g": 290, "protein_per_100g": 7.0, "carbs_per_100g": 43.0, "fat_per_100g": 9.5,
        "serving_description": "1 paratha (80g)", "serving_weight_g": 80,
    },
    {
        "food_name": "Aloo Paratha",
        "tags": ["aloo paratha", "potato paratha", "stuffed paratha"],
        "calories_per_100g": 280, "protein_per_100g": 6.5, "carbs_per_100g": 42.0, "fat_per_100g": 9.0,
        "serving_description": "1 paratha (90g)", "serving_weight_g": 90,
    },
    {
        "food_name": "Puri",
        "tags": ["puri", "poori", "fried bread"],
        "calories_per_100g": 365, "protein_per_100g": 8.0, "carbs_per_100g": 45.0, "fat_per_100g": 17.0,
        "serving_description": "1 puri (25g)", "serving_weight_g": 25,
    },
    {
        "food_name": "Naan",
        "tags": ["naan", "nan", "butter naan", "garlic naan", "tandoori naan"],
        "calories_per_100g": 280, "protein_per_100g": 9.0, "carbs_per_100g": 50.0, "fat_per_100g": 5.0,
        "serving_description": "1 naan (90g)", "serving_weight_g": 90,
    },
    {
        "food_name": "Bhatura",
        "tags": ["bhatura", "bhature", "fried bread"],
        "calories_per_100g": 340, "protein_per_100g": 8.0, "carbs_per_100g": 47.0, "fat_per_100g": 13.0,
        "serving_description": "1 bhatura (80g)", "serving_weight_g": 80,
    },
    {
        "food_name": "Bajra Roti",
        "tags": ["bajra roti", "pearl millet roti", "bajra bhakri"],
        "calories_per_100g": 241, "protein_per_100g": 11.0, "carbs_per_100g": 48.0, "fat_per_100g": 3.0,
        "serving_description": "1 roti (60g)", "serving_weight_g": 60,
    },
    {
        "food_name": "Jowar Roti",
        "tags": ["jowar roti", "sorghum roti", "jowar bhakri"],
        "calories_per_100g": 252, "protein_per_100g": 10.0, "carbs_per_100g": 50.0, "fat_per_100g": 2.0,
        "serving_description": "1 roti (60g)", "serving_weight_g": 60,
    },
    {
        "food_name": "Makki Roti",
        "tags": ["makki roti", "makka roti", "cornmeal roti"],
        "calories_per_100g": 254, "protein_per_100g": 8.0, "carbs_per_100g": 52.0, "fat_per_100g": 2.0,
        "serving_description": "1 roti (70g)", "serving_weight_g": 70,
    },
    {
        "food_name": "Thepla",
        "tags": ["thepla", "gujarati thepla", "methi thepla"],
        "calories_per_100g": 290, "protein_per_100g": 9.0, "carbs_per_100g": 42.0, "fat_per_100g": 10.0,
        "serving_description": "1 thepla (50g)", "serving_weight_g": 50,
    },
    # ─── SOUTH INDIAN ────────────────────────────────────────────────────────
    {
        "food_name": "Idli",
        "tags": ["idli", "steamed rice cake", "idly"],
        "calories_per_100g": 142, "protein_per_100g": 4.0, "carbs_per_100g": 29.0, "fat_per_100g": 0.4,
        "serving_description": "2 idlis (80g)", "serving_weight_g": 80,
    },
    {
        "food_name": "Plain Dosa",
        "tags": ["dosa", "plain dosa", "crispy dosa", "thin dosa"],
        "calories_per_100g": 175, "protein_per_100g": 4.0, "carbs_per_100g": 31.0, "fat_per_100g": 4.0,
        "serving_description": "1 dosa (80g)", "serving_weight_g": 80,
    },
    {
        "food_name": "Masala Dosa",
        "tags": ["masala dosa", "potato dosa", "south indian dosa"],
        "calories_per_100g": 155, "protein_per_100g": 4.0, "carbs_per_100g": 28.0, "fat_per_100g": 4.0,
        "serving_description": "1 masala dosa (150g)", "serving_weight_g": 150,
    },
    {
        "food_name": "Rava Dosa",
        "tags": ["rava dosa", "semolina dosa", "sooji dosa"],
        "calories_per_100g": 190, "protein_per_100g": 5.0, "carbs_per_100g": 30.0, "fat_per_100g": 6.0,
        "serving_description": "1 rava dosa (90g)", "serving_weight_g": 90,
    },
    {
        "food_name": "Uttapam",
        "tags": ["uttapam", "uthappam", "rice pancake"],
        "calories_per_100g": 145, "protein_per_100g": 4.0, "carbs_per_100g": 27.0, "fat_per_100g": 3.0,
        "serving_description": "1 uttapam (100g)", "serving_weight_g": 100,
    },
    {
        "food_name": "Sambhar",
        "tags": ["sambhar", "sambar", "lentil vegetable stew"],
        "calories_per_100g": 80, "protein_per_100g": 4.0, "carbs_per_100g": 13.0, "fat_per_100g": 2.0,
        "serving_description": "1 bowl (200ml)", "serving_weight_g": 200,
    },
    {
        "food_name": "Coconut Chutney",
        "tags": ["coconut chutney", "nariyal chutney"],
        "calories_per_100g": 220, "protein_per_100g": 3.0, "carbs_per_100g": 10.0, "fat_per_100g": 19.0,
        "serving_description": "2 tbsp (30g)", "serving_weight_g": 30,
    },
    {
        "food_name": "Rasam",
        "tags": ["rasam", "pepper rasam", "tomato rasam", "tamarind soup"],
        "calories_per_100g": 30, "protein_per_100g": 1.5, "carbs_per_100g": 5.0, "fat_per_100g": 0.5,
        "serving_description": "1 bowl (200ml)", "serving_weight_g": 200,
    },
    {
        "food_name": "Medu Vada",
        "tags": ["medu vada", "urad dal vada", "vada"],
        "calories_per_100g": 330, "protein_per_100g": 10.0, "carbs_per_100g": 35.0, "fat_per_100g": 16.0,
        "serving_description": "1 vada (50g)", "serving_weight_g": 50,
    },
    {
        "food_name": "Appam",
        "tags": ["appam", "hoppers", "rice appam", "palappam"],
        "calories_per_100g": 180, "protein_per_100g": 4.0, "carbs_per_100g": 35.0, "fat_per_100g": 3.0,
        "serving_description": "2 appams (80g)", "serving_weight_g": 80,
    },
    {
        "food_name": "Pesarattu",
        "tags": ["pesarattu", "moong dosa", "green gram dosa"],
        "calories_per_100g": 140, "protein_per_100g": 8.0, "carbs_per_100g": 20.0, "fat_per_100g": 3.0,
        "serving_description": "1 pesarattu (80g)", "serving_weight_g": 80,
    },
    # ─── BREAKFAST ───────────────────────────────────────────────────────────
    {
        "food_name": "Poha",
        "tags": ["poha", "beaten rice", "aval", "flattened rice", "pohe"],
        "calories_per_100g": 180, "protein_per_100g": 3.5, "carbs_per_100g": 36.0, "fat_per_100g": 4.0,
        "serving_description": "1 bowl (200g)", "serving_weight_g": 200,
    },
    {
        "food_name": "Upma",
        "tags": ["upma", "rava upma", "semolina upma", "sooji upma"],
        "calories_per_100g": 100, "protein_per_100g": 3.0, "carbs_per_100g": 18.0, "fat_per_100g": 2.5,
        "serving_description": "1 bowl (200g)", "serving_weight_g": 200,
    },
    {
        "food_name": "Sheera / Sooji Halwa",
        "tags": ["sheera", "sooji halwa", "rava halwa", "suji halwa", "semolina halwa"],
        "calories_per_100g": 315, "protein_per_100g": 4.0, "carbs_per_100g": 50.0, "fat_per_100g": 10.0,
        "serving_description": "1 serving (100g)", "serving_weight_g": 100,
    },
    # ─── DAL & LENTILS ───────────────────────────────────────────────────────
    {
        "food_name": "Toor Dal (Cooked)",
        "tags": ["toor dal", "arhar dal", "pigeon peas dal", "split pigeon pea"],
        "calories_per_100g": 116, "protein_per_100g": 7.0, "carbs_per_100g": 19.0, "fat_per_100g": 1.0,
        "serving_description": "1 bowl (200g)", "serving_weight_g": 200,
    },
    {
        "food_name": "Masoor Dal (Cooked)",
        "tags": ["masoor dal", "red lentil dal", "pink dal", "lentil dal"],
        "calories_per_100g": 118, "protein_per_100g": 8.0, "carbs_per_100g": 18.0, "fat_per_100g": 0.4,
        "serving_description": "1 bowl (200g)", "serving_weight_g": 200,
    },
    {
        "food_name": "Moong Dal (Cooked)",
        "tags": ["moong dal", "mung dal", "yellow moong dal", "split green gram"],
        "calories_per_100g": 105, "protein_per_100g": 7.0, "carbs_per_100g": 18.0, "fat_per_100g": 0.4,
        "serving_description": "1 bowl (200g)", "serving_weight_g": 200,
    },
    {
        "food_name": "Chana Dal (Cooked)",
        "tags": ["chana dal", "split chickpea dal", "bengal gram dal"],
        "calories_per_100g": 130, "protein_per_100g": 8.0, "carbs_per_100g": 20.0, "fat_per_100g": 2.0,
        "serving_description": "1 bowl (200g)", "serving_weight_g": 200,
    },
    {
        "food_name": "Urad Dal (Cooked)",
        "tags": ["urad dal", "black gram dal", "white urad dal", "split black gram"],
        "calories_per_100g": 105, "protein_per_100g": 7.0, "carbs_per_100g": 17.0, "fat_per_100g": 0.5,
        "serving_description": "1 bowl (200g)", "serving_weight_g": 200,
    },
    {
        "food_name": "Dal Fry",
        "tags": ["dal fry", "dal tadka", "tadka dal", "restaurant dal"],
        "calories_per_100g": 95, "protein_per_100g": 5.0, "carbs_per_100g": 12.0, "fat_per_100g": 3.0,
        "serving_description": "1 bowl (200g)", "serving_weight_g": 200,
    },
    {
        "food_name": "Dal Makhani",
        "tags": ["dal makhani", "black dal", "makhani dal", "urad dal makhani", "punjabi dal"],
        "calories_per_100g": 135, "protein_per_100g": 7.0, "carbs_per_100g": 15.0, "fat_per_100g": 5.5,
        "serving_description": "1 bowl (200g)", "serving_weight_g": 200,
    },
    {
        "food_name": "Rajma Curry",
        "tags": ["rajma", "kidney beans curry", "rajma chawal", "red beans"],
        "calories_per_100g": 120, "protein_per_100g": 7.0, "carbs_per_100g": 16.0, "fat_per_100g": 3.0,
        "serving_description": "1 bowl (200g)", "serving_weight_g": 200,
    },
    {
        "food_name": "Chole / Chana Masala",
        "tags": ["chole", "chana masala", "chickpea curry", "punjabi chole", "chhole"],
        "calories_per_100g": 130, "protein_per_100g": 7.0, "carbs_per_100g": 18.0, "fat_per_100g": 3.5,
        "serving_description": "1 bowl (200g)", "serving_weight_g": 200,
    },
    {
        "food_name": "Sprouted Moong",
        "tags": ["sprouted moong", "moong sprouts", "bean sprouts", "sprouts"],
        "calories_per_100g": 30, "protein_per_100g": 3.0, "carbs_per_100g": 6.0, "fat_per_100g": 0.2,
        "serving_description": "1 cup (100g)", "serving_weight_g": 100,
    },
    # ─── PANEER DISHES ───────────────────────────────────────────────────────
    {
        "food_name": "Paneer (Raw)",
        "tags": ["paneer", "cottage cheese", "fresh paneer"],
        "calories_per_100g": 265, "protein_per_100g": 18.0, "carbs_per_100g": 2.0, "fat_per_100g": 20.0,
        "serving_description": "100g block", "serving_weight_g": 100,
    },
    {
        "food_name": "Palak Paneer",
        "tags": ["palak paneer", "spinach paneer curry"],
        "calories_per_100g": 160, "protein_per_100g": 8.0, "carbs_per_100g": 8.0, "fat_per_100g": 11.0,
        "serving_description": "1 bowl (200g)", "serving_weight_g": 200,
    },
    {
        "food_name": "Paneer Butter Masala",
        "tags": ["paneer butter masala", "paneer makhani", "butter paneer"],
        "calories_per_100g": 175, "protein_per_100g": 9.0, "carbs_per_100g": 10.0, "fat_per_100g": 11.0,
        "serving_description": "1 bowl (200g)", "serving_weight_g": 200,
    },
    {
        "food_name": "Matar Paneer",
        "tags": ["matar paneer", "peas paneer curry", "mattar paneer"],
        "calories_per_100g": 145, "protein_per_100g": 7.0, "carbs_per_100g": 12.0, "fat_per_100g": 8.0,
        "serving_description": "1 bowl (200g)", "serving_weight_g": 200,
    },
    {
        "food_name": "Shahi Paneer",
        "tags": ["shahi paneer", "rich paneer curry", "creamy paneer"],
        "calories_per_100g": 200, "protein_per_100g": 9.0, "carbs_per_100g": 10.0, "fat_per_100g": 15.0,
        "serving_description": "1 bowl (200g)", "serving_weight_g": 200,
    },
    # ─── VEGETABLE DISHES ────────────────────────────────────────────────────
    {
        "food_name": "Aloo Sabzi",
        "tags": ["aloo sabzi", "potato curry", "aloo ki sabzi", "potato vegetable"],
        "calories_per_100g": 90, "protein_per_100g": 2.0, "carbs_per_100g": 15.0, "fat_per_100g": 3.0,
        "serving_description": "1 bowl (150g)", "serving_weight_g": 150,
    },
    {
        "food_name": "Aloo Gobi",
        "tags": ["aloo gobi", "potato cauliflower", "potato cauliflower curry"],
        "calories_per_100g": 80, "protein_per_100g": 2.5, "carbs_per_100g": 12.0, "fat_per_100g": 2.5,
        "serving_description": "1 bowl (150g)", "serving_weight_g": 150,
    },
    {
        "food_name": "Baingan Bharta",
        "tags": ["baingan bharta", "roasted eggplant", "brinjal bharta", "smoky eggplant"],
        "calories_per_100g": 75, "protein_per_100g": 2.0, "carbs_per_100g": 9.0, "fat_per_100g": 3.5,
        "serving_description": "1 bowl (150g)", "serving_weight_g": 150,
    },
    {
        "food_name": "Bhindi Fry",
        "tags": ["bhindi", "bhindi fry", "okra fry", "ladyfinger", "lady finger sabzi"],
        "calories_per_100g": 85, "protein_per_100g": 2.0, "carbs_per_100g": 8.0, "fat_per_100g": 4.5,
        "serving_description": "1 bowl (150g)", "serving_weight_g": 150,
    },
    {
        "food_name": "Methi Sabzi",
        "tags": ["methi", "methi sabzi", "fenugreek leaves", "methi ki sabzi"],
        "calories_per_100g": 65, "protein_per_100g": 4.0, "carbs_per_100g": 7.0, "fat_per_100g": 3.0,
        "serving_description": "1 bowl (150g)", "serving_weight_g": 150,
    },
    {
        "food_name": "Palak Dal",
        "tags": ["palak dal", "spinach dal", "spinach lentil"],
        "calories_per_100g": 100, "protein_per_100g": 5.5, "carbs_per_100g": 13.0, "fat_per_100g": 2.5,
        "serving_description": "1 bowl (200g)", "serving_weight_g": 200,
    },
    {
        "food_name": "Aloo Matar",
        "tags": ["aloo matar", "potato peas", "matar aloo", "potato green peas"],
        "calories_per_100g": 95, "protein_per_100g": 3.0, "carbs_per_100g": 14.0, "fat_per_100g": 3.5,
        "serving_description": "1 bowl (150g)", "serving_weight_g": 150,
    },
    {
        "food_name": "Sarson da Saag",
        "tags": ["sarson saag", "mustard greens curry", "punjabi saag", "sarson ka saag"],
        "calories_per_100g": 90, "protein_per_100g": 4.0, "carbs_per_100g": 10.0, "fat_per_100g": 4.0,
        "serving_description": "1 bowl (200g)", "serving_weight_g": 200,
    },
    {
        "food_name": "Kadhi",
        "tags": ["kadhi", "kadhi pakora", "besan kadhi", "yogurt curry"],
        "calories_per_100g": 65, "protein_per_100g": 3.0, "carbs_per_100g": 8.0, "fat_per_100g": 2.5,
        "serving_description": "1 bowl (200ml)", "serving_weight_g": 200,
    },
    # ─── NON-VEG DISHES ──────────────────────────────────────────────────────
    {
        "food_name": "Chicken Curry",
        "tags": ["chicken curry", "desi chicken curry", "murgh curry"],
        "calories_per_100g": 180, "protein_per_100g": 17.0, "carbs_per_100g": 5.0, "fat_per_100g": 10.0,
        "serving_description": "1 bowl (200g)", "serving_weight_g": 200,
    },
    {
        "food_name": "Butter Chicken",
        "tags": ["butter chicken", "murgh makhani", "chicken makhani", "tikka masala"],
        "calories_per_100g": 185, "protein_per_100g": 17.0, "carbs_per_100g": 7.0, "fat_per_100g": 10.0,
        "serving_description": "1 bowl (200g)", "serving_weight_g": 200,
    },
    {
        "food_name": "Chicken Tikka",
        "tags": ["chicken tikka", "tandoori chicken tikka", "grilled chicken tikka"],
        "calories_per_100g": 195, "protein_per_100g": 25.0, "carbs_per_100g": 4.0, "fat_per_100g": 9.0,
        "serving_description": "1 serving (150g)", "serving_weight_g": 150,
    },
    {
        "food_name": "Mutton Curry",
        "tags": ["mutton curry", "lamb curry", "gosht curry", "meat curry"],
        "calories_per_100g": 200, "protein_per_100g": 18.0, "carbs_per_100g": 4.0, "fat_per_100g": 13.0,
        "serving_description": "1 bowl (200g)", "serving_weight_g": 200,
    },
    {
        "food_name": "Fish Curry",
        "tags": ["fish curry", "meen curry", "machli curry", "fish masala"],
        "calories_per_100g": 150, "protein_per_100g": 14.0, "carbs_per_100g": 5.0, "fat_per_100g": 8.0,
        "serving_description": "1 bowl (200g)", "serving_weight_g": 200,
    },
    {
        "food_name": "Egg Curry",
        "tags": ["egg curry", "anda curry", "anda masala", "boiled egg curry"],
        "calories_per_100g": 140, "protein_per_100g": 10.0, "carbs_per_100g": 6.0, "fat_per_100g": 9.0,
        "serving_description": "2 eggs in curry (200g)", "serving_weight_g": 200,
    },
    {
        "food_name": "Keema",
        "tags": ["keema", "kheema", "minced meat", "mutton keema", "chicken keema"],
        "calories_per_100g": 220, "protein_per_100g": 20.0, "carbs_per_100g": 5.0, "fat_per_100g": 13.0,
        "serving_description": "1 bowl (150g)", "serving_weight_g": 150,
    },
    {
        "food_name": "Tandoori Chicken",
        "tags": ["tandoori chicken", "tandoori murgh", "grilled chicken", "oven chicken"],
        "calories_per_100g": 175, "protein_per_100g": 25.0, "carbs_per_100g": 3.0, "fat_per_100g": 7.0,
        "serving_description": "1 leg piece (150g)", "serving_weight_g": 150,
    },
    {
        "food_name": "Prawn Curry",
        "tags": ["prawn curry", "jhinga curry", "shrimp curry", "kolambi curry"],
        "calories_per_100g": 140, "protein_per_100g": 14.0, "carbs_per_100g": 4.0, "fat_per_100g": 7.0,
        "serving_description": "1 bowl (200g)", "serving_weight_g": 200,
    },
    # ─── DAIRY ───────────────────────────────────────────────────────────────
    {
        "food_name": "Curd / Dahi (Full Fat)",
        "tags": ["curd", "dahi", "yogurt", "plain curd", "homemade curd", "full fat curd"],
        "calories_per_100g": 60, "protein_per_100g": 3.5, "carbs_per_100g": 4.7, "fat_per_100g": 3.1,
        "serving_description": "1 bowl (150g)", "serving_weight_g": 150,
    },
    {
        "food_name": "Curd / Dahi (Low Fat)",
        "tags": ["low fat curd", "toned curd", "skimmed dahi", "low fat yogurt"],
        "calories_per_100g": 45, "protein_per_100g": 4.0, "carbs_per_100g": 5.0, "fat_per_100g": 1.0,
        "serving_description": "1 bowl (150g)", "serving_weight_g": 150,
    },
    {
        "food_name": "Ghee",
        "tags": ["ghee", "clarified butter", "desi ghee"],
        "calories_per_100g": 900, "protein_per_100g": 0.0, "carbs_per_100g": 0.0, "fat_per_100g": 100.0,
        "serving_description": "1 tsp (5g)", "serving_weight_g": 5,
    },
    {
        "food_name": "Lassi (Sweet)",
        "tags": ["lassi", "sweet lassi", "punjabi lassi"],
        "calories_per_100g": 78, "protein_per_100g": 3.5, "carbs_per_100g": 11.0, "fat_per_100g": 2.5,
        "serving_description": "1 glass (300ml)", "serving_weight_g": 300,
    },
    {
        "food_name": "Chaas / Buttermilk",
        "tags": ["chaas", "buttermilk", "lassi", "takra", "chhach", "mattha"],
        "calories_per_100g": 40, "protein_per_100g": 3.0, "carbs_per_100g": 4.8, "fat_per_100g": 1.0,
        "serving_description": "1 glass (250ml)", "serving_weight_g": 250,
    },
    {
        "food_name": "Milk (Full Fat / Buffalo)",
        "tags": ["milk", "full fat milk", "buffalo milk", "whole milk", "doodh"],
        "calories_per_100g": 66, "protein_per_100g": 3.3, "carbs_per_100g": 4.9, "fat_per_100g": 4.0,
        "serving_description": "1 glass (250ml)", "serving_weight_g": 250,
    },
    {
        "food_name": "Milk (Toned / Low Fat)",
        "tags": ["toned milk", "low fat milk", "skimmed milk", "slim milk"],
        "calories_per_100g": 44, "protein_per_100g": 3.1, "carbs_per_100g": 4.9, "fat_per_100g": 1.5,
        "serving_description": "1 glass (250ml)", "serving_weight_g": 250,
    },
    {
        "food_name": "Raita",
        "tags": ["raita", "boondi raita", "vegetable raita", "cucumber raita"],
        "calories_per_100g": 50, "protein_per_100g": 3.5, "carbs_per_100g": 5.0, "fat_per_100g": 1.5,
        "serving_description": "1 bowl (150g)", "serving_weight_g": 150,
    },
    # ─── EGGS & PROTEINS ─────────────────────────────────────────────────────
    {
        "food_name": "Boiled Egg",
        "tags": ["boiled egg", "hard boiled egg", "anda", "egg"],
        "calories_per_100g": 155, "protein_per_100g": 13.0, "carbs_per_100g": 1.0, "fat_per_100g": 11.0,
        "serving_description": "1 egg (50g)", "serving_weight_g": 50,
    },
    {
        "food_name": "Omelette",
        "tags": ["omelette", "omelet", "anda omelette", "egg omelette", "masala omelette"],
        "calories_per_100g": 175, "protein_per_100g": 12.0, "carbs_per_100g": 2.0, "fat_per_100g": 13.0,
        "serving_description": "1 omelette (100g)", "serving_weight_g": 100,
    },
    {
        "food_name": "Chicken Breast (Grilled)",
        "tags": ["chicken breast", "grilled chicken", "boneless chicken"],
        "calories_per_100g": 165, "protein_per_100g": 31.0, "carbs_per_100g": 0.0, "fat_per_100g": 3.6,
        "serving_description": "1 breast (150g)", "serving_weight_g": 150,
    },
    {
        "food_name": "Mutton / Goat Meat (Cooked)",
        "tags": ["mutton", "goat meat", "gosht", "lamb cooked"],
        "calories_per_100g": 234, "protein_per_100g": 25.0, "carbs_per_100g": 0.0, "fat_per_100g": 15.0,
        "serving_description": "1 serving (150g)", "serving_weight_g": 150,
    },
    {
        "food_name": "Rohu Fish (Cooked)",
        "tags": ["rohu", "rohu fish", "rohu machli"],
        "calories_per_100g": 97, "protein_per_100g": 17.0, "carbs_per_100g": 0.0, "fat_per_100g": 3.0,
        "serving_description": "1 serving (150g)", "serving_weight_g": 150,
    },
    # ─── STREET FOOD & SNACKS ────────────────────────────────────────────────
    {
        "food_name": "Samosa",
        "tags": ["samosa", "aloo samosa", "fried samosa"],
        "calories_per_100g": 262, "protein_per_100g": 5.0, "carbs_per_100g": 32.0, "fat_per_100g": 13.0,
        "serving_description": "1 samosa (80g)", "serving_weight_g": 80,
    },
    {
        "food_name": "Pakora / Bhajia",
        "tags": ["pakora", "pakoda", "bhajia", "fritters", "onion pakoda", "vegetable pakora"],
        "calories_per_100g": 255, "protein_per_100g": 7.0, "carbs_per_100g": 25.0, "fat_per_100g": 14.0,
        "serving_description": "4-5 pieces (100g)", "serving_weight_g": 100,
    },
    {
        "food_name": "Pav Bhaji",
        "tags": ["pav bhaji", "bombay pav bhaji", "street pav bhaji"],
        "calories_per_100g": 115, "protein_per_100g": 3.0, "carbs_per_100g": 17.0, "fat_per_100g": 4.0,
        "serving_description": "1 serving with 2 pav (300g)", "serving_weight_g": 300,
    },
    {
        "food_name": "Bhel Puri",
        "tags": ["bhel puri", "bhelpuri", "chaat", "mumbai bhel"],
        "calories_per_100g": 200, "protein_per_100g": 5.0, "carbs_per_100g": 35.0, "fat_per_100g": 5.0,
        "serving_description": "1 plate (150g)", "serving_weight_g": 150,
    },
    {
        "food_name": "Pani Puri / Gol Gappa",
        "tags": ["pani puri", "gol gappa", "golgappa", "puchka", "paani puri"],
        "calories_per_100g": 350, "protein_per_100g": 7.0, "carbs_per_100g": 60.0, "fat_per_100g": 9.0,
        "serving_description": "6 pieces (60g)", "serving_weight_g": 60,
    },
    {
        "food_name": "Vada Pav",
        "tags": ["vada pav", "batata vada pav", "mumbai vada pav"],
        "calories_per_100g": 185, "protein_per_100g": 5.0, "carbs_per_100g": 30.0, "fat_per_100g": 6.0,
        "serving_description": "1 vada pav (140g)", "serving_weight_g": 140,
    },
    {
        "food_name": "Kachori",
        "tags": ["kachori", "aloo kachori", "dal kachori", "pyaz kachori"],
        "calories_per_100g": 420, "protein_per_100g": 9.0, "carbs_per_100g": 53.0, "fat_per_100g": 19.0,
        "serving_description": "1 kachori (80g)", "serving_weight_g": 80,
    },
    {
        "food_name": "Dhokla",
        "tags": ["dhokla", "khaman dhokla", "gujarati dhokla", "steamed dhokla"],
        "calories_per_100g": 160, "protein_per_100g": 7.0, "carbs_per_100g": 28.0, "fat_per_100g": 2.5,
        "serving_description": "4 pieces (120g)", "serving_weight_g": 120,
    },
    {
        "food_name": "Murukku",
        "tags": ["murukku", "chakli", "rice murukku", "ribbon murukku"],
        "calories_per_100g": 475, "protein_per_100g": 8.0, "carbs_per_100g": 60.0, "fat_per_100g": 22.0,
        "serving_description": "5 pieces (50g)", "serving_weight_g": 50,
    },
    {
        "food_name": "Namkeen / Mixture",
        "tags": ["namkeen", "mixture", "farsan", "chanachur", "snack mix"],
        "calories_per_100g": 490, "protein_per_100g": 12.0, "carbs_per_100g": 57.0, "fat_per_100g": 25.0,
        "serving_description": "1 handful (30g)", "serving_weight_g": 30,
    },
    {
        "food_name": "Khakhra",
        "tags": ["khakhra", "gujarati khakhra", "crispy flatbread"],
        "calories_per_100g": 400, "protein_per_100g": 10.0, "carbs_per_100g": 65.0, "fat_per_100g": 11.0,
        "serving_description": "2 pieces (50g)", "serving_weight_g": 50,
    },
    {
        "food_name": "Masala Peanuts",
        "tags": ["masala peanuts", "spicy peanuts", "roasted peanuts", "groundnuts"],
        "calories_per_100g": 520, "protein_per_100g": 22.0, "carbs_per_100g": 45.0, "fat_per_100g": 28.0,
        "serving_description": "1 handful (30g)", "serving_weight_g": 30,
    },
    {
        "food_name": "Papad",
        "tags": ["papad", "papadum", "pappad", "urad papad", "roasted papad"],
        "calories_per_100g": 355, "protein_per_100g": 22.0, "carbs_per_100g": 55.0, "fat_per_100g": 3.0,
        "serving_description": "1 papad (10g)", "serving_weight_g": 10,
    },
    # ─── SWEETS & DESSERTS ───────────────────────────────────────────────────
    {
        "food_name": "Gulab Jamun",
        "tags": ["gulab jamun", "gulab jamun sweet", "indian sweet"],
        "calories_per_100g": 350, "protein_per_100g": 6.0, "carbs_per_100g": 54.0, "fat_per_100g": 12.0,
        "serving_description": "2 pieces (80g)", "serving_weight_g": 80,
    },
    {
        "food_name": "Rasgulla",
        "tags": ["rasgulla", "ras gulla", "bengali rasgulla", "rasgola"],
        "calories_per_100g": 186, "protein_per_100g": 7.0, "carbs_per_100g": 30.0, "fat_per_100g": 4.0,
        "serving_description": "2 pieces (80g)", "serving_weight_g": 80,
    },
    {
        "food_name": "Kheer",
        "tags": ["kheer", "rice kheer", "rice pudding", "payasam", "payesh"],
        "calories_per_100g": 145, "protein_per_100g": 4.0, "carbs_per_100g": 24.0, "fat_per_100g": 4.0,
        "serving_description": "1 bowl (150g)", "serving_weight_g": 150,
    },
    {
        "food_name": "Gajar Halwa",
        "tags": ["gajar halwa", "carrot halwa", "gajrela"],
        "calories_per_100g": 230, "protein_per_100g": 4.0, "carbs_per_100g": 35.0, "fat_per_100g": 8.0,
        "serving_description": "1 serving (150g)", "serving_weight_g": 150,
    },
    {
        "food_name": "Besan Laddoo",
        "tags": ["besan laddoo", "gram flour laddoo", "laddoo", "ladoo"],
        "calories_per_100g": 460, "protein_per_100g": 12.0, "carbs_per_100g": 57.0, "fat_per_100g": 21.0,
        "serving_description": "1 laddoo (50g)", "serving_weight_g": 50,
    },
    {
        "food_name": "Motichur Laddoo",
        "tags": ["motichur laddoo", "motichoor laddoo", "laddu"],
        "calories_per_100g": 440, "protein_per_100g": 7.0, "carbs_per_100g": 63.0, "fat_per_100g": 18.0,
        "serving_description": "1 laddoo (45g)", "serving_weight_g": 45,
    },
    {
        "food_name": "Jalebi",
        "tags": ["jalebi", "imarti", "funnel cake indian"],
        "calories_per_100g": 387, "protein_per_100g": 3.0, "carbs_per_100g": 71.0, "fat_per_100g": 10.0,
        "serving_description": "3 pieces (80g)", "serving_weight_g": 80,
    },
    {
        "food_name": "Barfi / Burfi",
        "tags": ["barfi", "burfi", "milk barfi", "kaju barfi", "coconut barfi"],
        "calories_per_100g": 390, "protein_per_100g": 8.0, "carbs_per_100g": 60.0, "fat_per_100g": 14.0,
        "serving_description": "2 pieces (60g)", "serving_weight_g": 60,
    },
    {
        "food_name": "Kulfi",
        "tags": ["kulfi", "malai kulfi", "pista kulfi", "indian ice cream"],
        "calories_per_100g": 180, "protein_per_100g": 5.0, "carbs_per_100g": 25.0, "fat_per_100g": 7.0,
        "serving_description": "1 stick (80g)", "serving_weight_g": 80,
    },
    {
        "food_name": "Mysore Pak",
        "tags": ["mysore pak", "mysurpa", "besan sweet"],
        "calories_per_100g": 480, "protein_per_100g": 8.0, "carbs_per_100g": 55.0, "fat_per_100g": 26.0,
        "serving_description": "1 piece (50g)", "serving_weight_g": 50,
    },
    # ─── BEVERAGES ───────────────────────────────────────────────────────────
    {
        "food_name": "Chai (Milk Tea with Sugar)",
        "tags": ["chai", "tea", "milk tea", "masala chai", "ginger chai", "indian tea"],
        "calories_per_100g": 55, "protein_per_100g": 2.0, "carbs_per_100g": 8.0, "fat_per_100g": 1.5,
        "serving_description": "1 cup (150ml)", "serving_weight_g": 150,
    },
    {
        "food_name": "Filter Coffee",
        "tags": ["filter coffee", "south indian coffee", "coffee", "kaapi"],
        "calories_per_100g": 45, "protein_per_100g": 1.5, "carbs_per_100g": 6.0, "fat_per_100g": 1.5,
        "serving_description": "1 cup (150ml)", "serving_weight_g": 150,
    },
    {
        "food_name": "Mango Lassi",
        "tags": ["mango lassi", "aam lassi", "fruit lassi"],
        "calories_per_100g": 95, "protein_per_100g": 3.0, "carbs_per_100g": 17.0, "fat_per_100g": 2.0,
        "serving_description": "1 glass (250ml)", "serving_weight_g": 250,
    },
    {
        "food_name": "Nimbu Pani",
        "tags": ["nimbu pani", "lemon water", "lemonade", "shikanji", "lemon juice"],
        "calories_per_100g": 35, "protein_per_100g": 0.0, "carbs_per_100g": 9.0, "fat_per_100g": 0.0,
        "serving_description": "1 glass (250ml)", "serving_weight_g": 250,
    },
    {
        "food_name": "Coconut Water",
        "tags": ["coconut water", "naariyal pani", "tender coconut water"],
        "calories_per_100g": 20, "protein_per_100g": 0.7, "carbs_per_100g": 4.0, "fat_per_100g": 0.2,
        "serving_description": "1 coconut (250ml)", "serving_weight_g": 250,
    },
    {
        "food_name": "Aam Panna",
        "tags": ["aam panna", "raw mango drink", "kaccha aam", "kairi drink"],
        "calories_per_100g": 55, "protein_per_100g": 0.5, "carbs_per_100g": 14.0, "fat_per_100g": 0.0,
        "serving_description": "1 glass (250ml)", "serving_weight_g": 250,
    },
    # ─── FRUITS ──────────────────────────────────────────────────────────────
    {
        "food_name": "Mango (Alphonso / Kesar)",
        "tags": ["mango", "aam", "alphonso", "kesar mango", "hapus"],
        "calories_per_100g": 60, "protein_per_100g": 0.8, "carbs_per_100g": 15.0, "fat_per_100g": 0.4,
        "serving_description": "1 medium (200g)", "serving_weight_g": 200,
    },
    {
        "food_name": "Banana",
        "tags": ["banana", "kela", "plantain"],
        "calories_per_100g": 89, "protein_per_100g": 1.1, "carbs_per_100g": 23.0, "fat_per_100g": 0.3,
        "serving_description": "1 medium (120g)", "serving_weight_g": 120,
    },
    {
        "food_name": "Apple",
        "tags": ["apple", "seb", "green apple", "red apple"],
        "calories_per_100g": 52, "protein_per_100g": 0.3, "carbs_per_100g": 14.0, "fat_per_100g": 0.2,
        "serving_description": "1 medium (180g)", "serving_weight_g": 180,
    },
    {
        "food_name": "Papaya",
        "tags": ["papaya", "papita", "raw papaya", "ripe papaya"],
        "calories_per_100g": 43, "protein_per_100g": 0.5, "carbs_per_100g": 11.0, "fat_per_100g": 0.3,
        "serving_description": "1 cup diced (150g)", "serving_weight_g": 150,
    },
    {
        "food_name": "Guava",
        "tags": ["guava", "amrood", "peru"],
        "calories_per_100g": 68, "protein_per_100g": 2.6, "carbs_per_100g": 14.0, "fat_per_100g": 1.0,
        "serving_description": "1 medium (120g)", "serving_weight_g": 120,
    },
    {
        "food_name": "Pomegranate",
        "tags": ["pomegranate", "anar", "anardana"],
        "calories_per_100g": 83, "protein_per_100g": 1.7, "carbs_per_100g": 19.0, "fat_per_100g": 1.2,
        "serving_description": "100g seeds", "serving_weight_g": 100,
    },
    {
        "food_name": "Watermelon",
        "tags": ["watermelon", "tarbooz", "tarbuj"],
        "calories_per_100g": 30, "protein_per_100g": 0.6, "carbs_per_100g": 7.5, "fat_per_100g": 0.2,
        "serving_description": "2 cups (300g)", "serving_weight_g": 300,
    },
    {
        "food_name": "Orange / Mosambi",
        "tags": ["orange", "mosambi", "sweet lime", "nagpur orange", "narangi"],
        "calories_per_100g": 47, "protein_per_100g": 0.9, "carbs_per_100g": 12.0, "fat_per_100g": 0.1,
        "serving_description": "1 medium (150g)", "serving_weight_g": 150,
    },
    {
        "food_name": "Grapes",
        "tags": ["grapes", "angoor", "green grapes", "black grapes"],
        "calories_per_100g": 67, "protein_per_100g": 0.6, "carbs_per_100g": 17.0, "fat_per_100g": 0.4,
        "serving_description": "1 cup (150g)", "serving_weight_g": 150,
    },
    # ─── VEGETABLES ──────────────────────────────────────────────────────────
    {
        "food_name": "Boiled Potato",
        "tags": ["potato", "aloo", "boiled potato", "plain potato"],
        "calories_per_100g": 77, "protein_per_100g": 2.0, "carbs_per_100g": 17.0, "fat_per_100g": 0.1,
        "serving_description": "1 medium (150g)", "serving_weight_g": 150,
    },
    {
        "food_name": "Sweet Potato",
        "tags": ["sweet potato", "shakarkandi", "shakarkand"],
        "calories_per_100g": 76, "protein_per_100g": 1.6, "carbs_per_100g": 18.0, "fat_per_100g": 0.1,
        "serving_description": "1 medium (150g)", "serving_weight_g": 150,
    },
    {
        "food_name": "Spinach (Palak)",
        "tags": ["spinach", "palak", "cooked spinach"],
        "calories_per_100g": 23, "protein_per_100g": 3.0, "carbs_per_100g": 3.6, "fat_per_100g": 0.3,
        "serving_description": "1 bowl (100g)", "serving_weight_g": 100,
    },
    {
        "food_name": "Tomato",
        "tags": ["tomato", "tamatar", "raw tomato"],
        "calories_per_100g": 18, "protein_per_100g": 0.9, "carbs_per_100g": 3.9, "fat_per_100g": 0.2,
        "serving_description": "1 medium (120g)", "serving_weight_g": 120,
    },
    {
        "food_name": "Onion",
        "tags": ["onion", "pyaz", "kanda", "raw onion"],
        "calories_per_100g": 40, "protein_per_100g": 1.1, "carbs_per_100g": 9.3, "fat_per_100g": 0.1,
        "serving_description": "1 medium (100g)", "serving_weight_g": 100,
    },
    {
        "food_name": "Bottle Gourd (Lauki / Dudhi)",
        "tags": ["lauki", "dudhi", "bottle gourd", "ghia"],
        "calories_per_100g": 14, "protein_per_100g": 0.6, "carbs_per_100g": 3.4, "fat_per_100g": 0.1,
        "serving_description": "1 bowl (150g)", "serving_weight_g": 150,
    },
    {
        "food_name": "Bitter Gourd (Karela)",
        "tags": ["karela", "bitter gourd", "bitter melon", "pavakkai"],
        "calories_per_100g": 17, "protein_per_100g": 1.0, "carbs_per_100g": 3.7, "fat_per_100g": 0.2,
        "serving_description": "1 bowl (100g)", "serving_weight_g": 100,
    },
    {
        "food_name": "Drumstick (Moringa)",
        "tags": ["drumstick", "moringa", "sahjan", "murungakkai"],
        "calories_per_100g": 37, "protein_per_100g": 2.5, "carbs_per_100g": 8.5, "fat_per_100g": 0.1,
        "serving_description": "100g", "serving_weight_g": 100,
    },
    # ─── NUTS & DRY FRUITS ───────────────────────────────────────────────────
    {
        "food_name": "Cashews (Kaju)",
        "tags": ["cashews", "kaju", "raw cashews", "roasted cashews"],
        "calories_per_100g": 553, "protein_per_100g": 18.0, "carbs_per_100g": 30.0, "fat_per_100g": 44.0,
        "serving_description": "1 handful (30g)", "serving_weight_g": 30,
    },
    {
        "food_name": "Almonds (Badam)",
        "tags": ["almonds", "badam", "raw almonds", "soaked almonds"],
        "calories_per_100g": 579, "protein_per_100g": 21.0, "carbs_per_100g": 22.0, "fat_per_100g": 50.0,
        "serving_description": "1 handful (30g)", "serving_weight_g": 30,
    },
    {
        "food_name": "Walnuts (Akhrot)",
        "tags": ["walnuts", "akhrot", "walnut halves"],
        "calories_per_100g": 654, "protein_per_100g": 15.0, "carbs_per_100g": 14.0, "fat_per_100g": 65.0,
        "serving_description": "1 handful (30g)", "serving_weight_g": 30,
    },
    {
        "food_name": "Peanuts / Groundnuts",
        "tags": ["peanuts", "groundnuts", "moongphali", "raw peanuts"],
        "calories_per_100g": 567, "protein_per_100g": 26.0, "carbs_per_100g": 16.0, "fat_per_100g": 49.0,
        "serving_description": "1 handful (30g)", "serving_weight_g": 30,
    },
    {
        "food_name": "Dates (Khajoor)",
        "tags": ["dates", "khajoor", "medjool dates"],
        "calories_per_100g": 282, "protein_per_100g": 2.5, "carbs_per_100g": 75.0, "fat_per_100g": 0.4,
        "serving_description": "3 dates (45g)", "serving_weight_g": 45,
    },
    {
        "food_name": "Raisins (Kishmish)",
        "tags": ["raisins", "kishmish", "dried grapes"],
        "calories_per_100g": 299, "protein_per_100g": 3.0, "carbs_per_100g": 79.0, "fat_per_100g": 0.5,
        "serving_description": "1 tbsp (20g)", "serving_weight_g": 20,
    },
    # ─── GRAINS & FLOUR ──────────────────────────────────────────────────────
    {
        "food_name": "Oats (Rolled)",
        "tags": ["oats", "rolled oats", "oatmeal", "quaker oats"],
        "calories_per_100g": 379, "protein_per_100g": 13.0, "carbs_per_100g": 67.0, "fat_per_100g": 7.0,
        "serving_description": "1/2 cup dry (45g)", "serving_weight_g": 45,
    },
    {
        "food_name": "Cooked Oatmeal",
        "tags": ["cooked oats", "oatmeal", "oat porridge", "daliya oats"],
        "calories_per_100g": 71, "protein_per_100g": 2.5, "carbs_per_100g": 12.0, "fat_per_100g": 1.5,
        "serving_description": "1 bowl (250g)", "serving_weight_g": 250,
    },
    {
        "food_name": "Wheat Flour (Atta)",
        "tags": ["atta", "wheat flour", "whole wheat flour", "gehu ka atta"],
        "calories_per_100g": 341, "protein_per_100g": 12.0, "carbs_per_100g": 70.0, "fat_per_100g": 2.0,
        "serving_description": "100g", "serving_weight_g": 100,
    },
    {
        "food_name": "Besan (Chickpea Flour)",
        "tags": ["besan", "chickpea flour", "gram flour", "chana flour"],
        "calories_per_100g": 387, "protein_per_100g": 22.0, "carbs_per_100g": 58.0, "fat_per_100g": 6.0,
        "serving_description": "100g", "serving_weight_g": 100,
    },
    {
        "food_name": "Dalia (Broken Wheat)",
        "tags": ["dalia", "broken wheat", "daliya", "lapsi"],
        "calories_per_100g": 118, "protein_per_100g": 4.5, "carbs_per_100g": 23.0, "fat_per_100g": 0.5,
        "serving_description": "1 bowl cooked (200g)", "serving_weight_g": 200,
    },
    # ─── POPULAR PACKAGED / BRANDED ──────────────────────────────────────────
    {
        "food_name": "Parle-G Biscuits",
        "brand": "Parle",
        "tags": ["parle g", "glucose biscuit", "parle biscuit", "parle-g"],
        "calories_per_100g": 451, "protein_per_100g": 7.0, "carbs_per_100g": 72.0, "fat_per_100g": 15.0,
        "serving_description": "4 biscuits (25g)", "serving_weight_g": 25,
    },
    {
        "food_name": "Marie Biscuits",
        "brand": "Britannia / Parle",
        "tags": ["marie biscuit", "marie gold", "marie"],
        "calories_per_100g": 396, "protein_per_100g": 7.0, "carbs_per_100g": 72.0, "fat_per_100g": 9.0,
        "serving_description": "4 biscuits (25g)", "serving_weight_g": 25,
    },
    {
        "food_name": "Maggi Noodles (Cooked)",
        "brand": "Nestle",
        "tags": ["maggi", "maggi noodles", "instant noodles"],
        "calories_per_100g": 165, "protein_per_100g": 5.0, "carbs_per_100g": 23.0, "fat_per_100g": 6.0,
        "serving_description": "1 packet cooked (280g)", "serving_weight_g": 280,
    },
    {
        "food_name": "Haldirams Bhujia",
        "brand": "Haldirams",
        "tags": ["bhujia", "haldirams bhujia", "aloo bhujia", "sev bhujia"],
        "calories_per_100g": 536, "protein_per_100g": 16.0, "carbs_per_100g": 54.0, "fat_per_100g": 28.0,
        "serving_description": "1 handful (30g)", "serving_weight_g": 30,
    },
    {
        "food_name": "Amul Butter",
        "brand": "Amul",
        "tags": ["amul butter", "butter", "desi butter", "salted butter"],
        "calories_per_100g": 720, "protein_per_100g": 0.5, "carbs_per_100g": 0.8, "fat_per_100g": 80.0,
        "serving_description": "1 tsp (10g)", "serving_weight_g": 10,
    },
    {
        "food_name": "Amul Cheese Slice",
        "brand": "Amul",
        "tags": ["amul cheese", "cheese slice", "processed cheese"],
        "calories_per_100g": 315, "protein_per_100g": 20.0, "carbs_per_100g": 2.0, "fat_per_100g": 25.0,
        "serving_description": "1 slice (20g)", "serving_weight_g": 20,
    },
    {
        "food_name": "Cornflakes",
        "brand": "Kellogg's",
        "tags": ["cornflakes", "corn flakes", "breakfast cereal", "kelloggs"],
        "calories_per_100g": 357, "protein_per_100g": 8.0, "carbs_per_100g": 84.0, "fat_per_100g": 0.6,
        "serving_description": "1 bowl dry (40g)", "serving_weight_g": 40,
    },
    # ─── CONDIMENTS ──────────────────────────────────────────────────────────
    {
        "food_name": "Green Chutney",
        "tags": ["green chutney", "mint chutney", "coriander chutney", "hari chutney"],
        "calories_per_100g": 65, "protein_per_100g": 3.0, "carbs_per_100g": 8.0, "fat_per_100g": 2.0,
        "serving_description": "2 tbsp (30g)", "serving_weight_g": 30,
    },
    {
        "food_name": "Mango Pickle (Achar)",
        "tags": ["achar", "pickle", "mango pickle", "aam ka achar", "mixed pickle"],
        "calories_per_100g": 75, "protein_per_100g": 0.5, "carbs_per_100g": 8.0, "fat_per_100g": 4.0,
        "serving_description": "1 tsp (10g)", "serving_weight_g": 10,
    },
]
